on:
  push:
    branches:
      [master, main]
  pull_request:
    branches:
      [master, main]

  os: linux
  dist: xenial

  language: node_js

  node_js:
    version:
      - lts
  npm:
    version:
      - lts

  script:
    - echo 'Starting Build'
    - echo 'Running Test'
    - npm run test
    - echo 'Test Complete'

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: change
    on_failure: always
