# This action deletes versions of a package from GitHub Packages except ghcr packages. This action will only delete a maximum of 99 versions in one run.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/delete-package-versions
name: Delete Package Versions

on:
  schedule:
    - cron: "0 2 1 1-12 *"

jobs:
  delete-package-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v3
        with:
          repo-token: "{{ secrets.GPR_READ_DELETE }}"
          package-name: "@killshot13/mj-pa"
          min-versions-to-keep: 2
